### PR TITLE
Added Manash Raja

### PR DESCRIPTION
**Pull request by ManashRaja**
I have added my name to the list.

### CODE REVIEW

**Comment by narayanaditya95** [comment]
Looks good to me. (y)

**Comment by abinashmeher999** [comment]
There are merge conflicts. Resolve them using rebase.

**Comment by hargup** [comment]
Hi @ManashRaja  we have changed the format to enter your name, see the commit message of https://github.com/AGV-IIT-KGP/git-sandbox/commit/095b8a39ab812ffa5b1fe933208dcbddcfff7f17 to know the new format and the reasons for the changes.

You need to rebase your pull request with the latest master. To know more about git-rebasing read http://git-scm.com/book/en/v2/Git-Branching-Rebasing Please don't hesitate to ask questions when you can't figure things out.

**Comment by routeaccess** [comment]
@ManashRaja Please notice that the format of entering your details has changed (as per pull request #26) , causing your changes to be stale/obsolete. Please rebase your changes to the latest commit in master branch. 
[Here](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) is a detailed explanation.

In addition:
- Please squash your commits into a single commit, as explained in the given link. 
- Mention the name being added in your commit message.
Refer to previous commits and pull-requests for reference.

**Pull request closed without merging**
