### PR TITLE
Merge pull request in branch partha

### PR DESCRIPTION
**Pull request by parthamishra1996**

### CODE REVIEW

**Comment by krishna95** [comment]
@parthamishra1996 Please resolve merge conflicts and a better commit message please.

**Comment by parthamishra1996** [comment]
Do i have to create another pull request?! or will this one do?

**Comment by krishna95** [comment]
@parthamishra1996 please squash the commits using git rebase master -i

**Comment by parthamishra1996** [comment]
Is it okay now?

**Pull request closed without merging**
