### PR TITLE
name added- Satyesh Mundra

### PR DESCRIPTION
**Pull request by satyeshmundra**
@krishna95

### CODE REVIEW

**Comment by satyeshmundra** [comment]
@krishna95

**Comment by krishna95** [comment]
@satyeshmundra Please have a better and unique commit message. Reading the logs should tell us which name was addded

**Comment by shivamvats** [comment]
@satyeshmundra Please make the requested changes.

**Comment by abinashmeher999** [comment]
@satyeshmundra Could you make the changes that were asked. This has been pending for long.

**Pull request closed without merging**
