### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by todivasudha**

### CODE REVIEW

**Comment by hargup** [comment]
And you need to write a better commit message, see other comments on commit messages https://github.com/AGV-IIT-KGP/git-sandbox/pull/29#issuecomment-76673134

**Comment by krishna95** [comment]
@todivasudha Please resolve merge conflicts and a better commit message please.

**Comment by todivasudha** [comment]
am not being able to resolve merge conflicts

**Comment by hargup** [comment]
> am not being able to resolve merge conflicts

@todivasudha 
If you are asking for help then please ask a better question. It is prefectly fine to make mistakes. Tell us what have you tried, what happened, what error messages you got and exactly where you got struct.

**Pull request closed without merging**
