### PR TITLE
added details

### PR DESCRIPTION
**Pull request by srichandra**

### CODE REVIEW

**Comment by krishna95** [comment]
@srichandra Please change the commit message to a new and better one. Reading the logs should tell which name was added

**Comment by srichandra** [comment]
@krishna95  Yeah! I changed the commit message

**Comment by krishna95** [comment]
@hargup @srichandra It looks good to me

**Comment by hargup** [comment]
@krishna95 cool go ahead and merge the pull request. If you don't have push access contact me.

**Pull request merged**
