### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by aranyadan**
added my name (Aranya)

### CODE REVIEW

**Comment by narayanaditya95** [comment]
@aranyadan Please resolve merge conflicts. Also, choose a better commit message.

**Comment by aranyadan** [comment]
i added only one line....how do i view the conflicts?

**Comment by krishna95** [comment]
@aranyadan You have merge conflicts because you haven't pulled recently. The one on which you made changes and pushed is an outdated one.

**Comment by hargup** [comment]
Hi @aranyadan we have changed the format to enter your name, see the commit message of https://github.com/AGV-IIT-KGP/git-sandbox/commit/095b8a39ab812ffa5b1fe933208dcbddcfff7f17 to know the new format and the reasons for the changes.

You need to rebase your pull request with the latest master. To know more about git-rebasing read http://git-scm.com/book/en/v2/Git-Branching-Rebasing Please don't hesitate to ask questions when you can't figure things out.

**Comment by routeaccess** [comment]
@aranyadan Please notice that the format of entering your details has changed (as per pull request #26) , causing your changes to be stale/obsolete. Please rebase your changes to the latest commit in master branch. 
[Here](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) is a detailed explanation.

In addition:
- Mention the name being added in your commit message.
- Edit the PR description above likewise.
Refer to previous commits and pull-requests for reference.

**Comment by aranyadan** [comment]
how to push to this particular branch?
"git push origin" edited on the master branch which is currently of the correct format and up to date
"git push origin new" is giving the error-
error: src refspec new does not match any.
error: failed to push some refs to 'https://github.com/aranyadan/git-sandbox.git'

**Comment by routeaccess** [comment]
@aranyadan Instead of rebasing and modifying your commits like you should have done, you have added more commits and introduced merges within the pull request. Merge commits within a PR is not a good practice.

- When you send a PR please ensure that the PR is just as you wish to be, by checking out the 'Commits' and 'Files changed' tabs on top of the PR page. If something is wrong/ change it immediately.
- You will see that there are 5 commits queued in your PR which should actually be one single commit, under the 'Commits' tab. Please squash your commits to a single commit.
- You will see that you're introducing more changes other than the one line you edited as part of this PR, in the 'Files changed' tab. The merge markers from when you tried to merge (which you should not do in a PR as a good practice) the master branch still remain in your file.

**Pull request closed without merging**
