### PR TITLE
added name

### PR DESCRIPTION
**Pull request by shadow-stranger**
Just another name to add...

### CODE REVIEW

**Comment by shadow-stranger** [comment]
closing, not a proper commit message I suppose

**Comment by abinashmeher999** [comment]
Hey @shadow-stranger, you do not close PRs just because you had improper commit message or disordered commits, or any similar reversible/rectifiable errors. You simply need to execute `git rebase -i HEAD~1` and follow the directions given to rectify the commit message and force push the changes. That should do it. Read about more about `rebase`, if you are interested.

**Comment by shadow-stranger** [comment]
I know about rebase (not the whole thing but enough to use it ) and I don't suppose it will change commits once it is in in a pull request in this case I just used `git commit --amend` to edit my last previous commit and force pushed it. (if rebase does changes commits in pull request too then please correct me) Although in normal cases when most people (who have forked your repo etc.) will find it very difficult to collaborate when you rebase and force push your commits, I suppose. Generally I try to avoid force pushes. Also better to start following git flow (or something like that). It helps. I am just trying those in my private repos.

**Comment by shadow-stranger** [comment]
And yes , in `git commit --amend` (which is a short version of rebase i suppose) with force push, I have to make a new pull request as the older pull request still contains the old commit. Hence I closed this pull request.

**Comment by abinashmeher999** [comment]
> I know about rebase (not the whole thing but enough to use it ) and I don't suppose it will change commits once it is in in a pull request in this case I just used git commit --amend to edit my last previous commit and force pushed it. (if rebase does changes commits in pull request too then please correct me)

I was talking about interactive rebase(`git rebase -i`). Eventually you end up doing `git commit --amend` only. It guides you through that.

> Although in normal cases when most people (who have forked your repo etc.) will find it very difficult to collaborate when you rebase and force push your commits, I suppose.

Yes, they will. That's why you never push or rebase the master branch. That's where the working and reviewed code is kept.

> And yes , in git commit --amend (which is a short version of rebase i suppose) with force push, I have to make a new pull request as the older pull request still contains the old commit. Hence I closed this pull request.

If you are doing a forced update on the same branch(the one you want to merge with the PR) then you don't need to open a new PR. The branch is just a online copy of your local branch that gets updated. The changes will still be visible in the PR. There is no more an old commit and a new commit once you forced update it. Your online copy of the branch will have the same content as the local copy of your branch.

**Comment by shadow-stranger** [comment]
Hmm.. Alright let me try it and see , so you are saying no matter what the pull request whether a closed or already a merged one will change it's commit ? That doesn't seem logical though. But then in my experience with git, it is not as preservative as mercurial. Will you except a new pull request or should I try in this only ?

**Comment by abinashmeher999** [comment]
> so you are saying no matter what the pull request whether a closed or already a merged one will change it's commit

I am saying:
- You cannot have multiple PRs *open* from the same branch
- If you have a PR open, then if you do a forced update to the branch(the one you want to merge) the same changes will be visible in the PR too.

I have already merged that other PR I think. If you want to try things out, you can send a pull request from one of the branches in your repo to the master in your repo itself. Then you can do a forced update and see if that is what happens.

**Comment by shadow-stranger** [comment]
Alright , I will comment here if I see anything contradictory after trying things out.

**Comment by shadow-stranger** [comment]
> I was talking about interactive rebase(git rebase -i). Eventually you end up doing git commit   `--amend` only. It guides you through that.

So...

I have tried both `git rebase -i` (with reword) and `git commit --amend` for editing last commit. Both works for open pull requests with forced push.  Just that they should be in the same branch (like for dev then in dev and not in any feature branch)

**Pull request closed without merging**
