### PR TITLE
Creating a new pull request as I had problems with the previous one.

### PR DESCRIPTION
**Pull request by ManashRaja**
I faced problems removing the conflicts, so since the previous pull request was closed, therefore I am creating a new pull request.

### CODE REVIEW

**Comment by abinashmeher999** [comment]
@ManashRaja it's not a good practice to create a new pull request to correct the problem you had with an old one. The purpose of this task is not to add your name, but to let you learn git by adding your name. So, I suggest you to try reopening the new one. If you are facing problems ask seniors.

**Comment by ManashRaja** [comment]
All my commits will now come to this pull request. I won't make any new pull request from now on... Also my previous pull request had problems since I reforked this repository.. But I have learnt now. I would continue with this pull request.

**Comment by hargup** [comment]
@ManashRaja Please improve your commit message see https://www.mediawiki.org/wiki/Gerrit/Commit_message_guidelines

**Comment by ManashRaja** [comment]
I modified the commit message.

**Pull request merged**
