### PR TITLE
Add my name to README (Abinash Senapati)

### PR DESCRIPTION
**Pull request by abinash08**

### CODE REVIEW

**Comment by abinashmeher999** [comment]
@abinash08 You do not create a new PR unless it is absolutely necessary. The remarks that were left in this PR should be corrected in this itself. Whatever changes you push to this branch will reflect here. I don't know why this PR shows `unknown repository`, maybe you deleted the fork.

Google on how to rebase branches and change history. The purpose of this PR is to learn, so I suggest you have patience and get this merged. It will be worth the effort.
 
@icyflame Do you know why this shows `unknown repository`?

**Comment by abinash08** [comment]
i was unable to use last repository for making changes. so created a new repository in which i rebased the master and deleted the last one.

**Comment by abinashmeher999** [comment]
That's ok. You could have asked for help. I am sure it wouldn't have been something impossible. It would have helped both of us learn git if it might have been something never seen before. Although I don't encourage this, I am closing this pull request for now since nothing can be done after you have deleted your repo. Please make any other changes that we point out in https://github.com/AGV-IIT-KGP/git-sandbox/pull/130 in the same branch.

**Comment by icyflame** [comment]
@abinashmeher999 It is very common among GitHub beginners to simply delete the repository, and fork a second time. (This fixes the problem of rebasing, etc, in a very ugly manner, ew.)

This leads to GitHub losing the branch that this PR was created from, and thus, we also lose the discussion that was done here, as well as the branch information, and all other meta-data.

**Pull request closed without merging**
