### PR TITLE
Create Kelechi

### PR DESCRIPTION
**Pull request by kelechithefuture**

### CODE REVIEW

**Comment by KelechiBenny** [comment]
If this actually worked, just wanted to say it wasn't easy!

**Comment by narayanaditya95** [comment]
@KelechiBenny Why create a new file? Add your name to the README.md. Make sure you pull from AGV-IIT-KGP/git-sandbox:master so that you dont face merge conflicts. And pls better commit messages.

**Comment by hargup** [comment]
> If this actually worked, just wanted to say it wasn't easy!

Unfortunately it did not work, but it is great that you are trying. As Aditya told in the previous comment you to make changes in the README.md and now you should use the new entry format. See the commmit message of https://github.com/AGV-IIT-KGP/git-sandbox/commit/095b8a39ab812ffa5b1fe933208dcbddcfff7f17

**Comment by routeaccess** [comment]
@KelechiBenny  Please notice that the format of entering your details has changed (as per pull request #26) , causing your changes to be stale/obsolete. Please rebase your changes to the latest commit in master branch. 
[Here](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) is a detailed explanation.
In addition:
- Mention the name being added in your commit message.
- Edit the pull-request description above to something more descriptive.
Refer to previous commits and pull-requests for more details.

**Pull request closed without merging**
