### PR TITLE
Fix several erroneous merges (#86, #96, #100, #103, #111, #51)

### PR DESCRIPTION
**Pull request by icyflame**

### CODE REVIEW

**Comment by abinashmeher999** [comment]
Thanks a lot. +1 to merge.

**Comment by abinashmeher999** [comment]
Should line 47 be corrected?

**Comment by icyflame** [comment]
I don't understand, 47 seems to be in the proper order. Section 44-50 seems fine to me.

**Comment by abinashmeher999** [comment]
I was trying to point out the missing space after the name.

**Comment by icyflame** [comment]
Updated, please review.

**Comment by abinashmeher999** [comment]
+1 to merge. @hargup ?

**Comment by icyflame** [comment]
@abinashmeher999 Actually, I found two more mistakes in the alphabetical order (while writing a node script to check the order, coming up soon, bundled inside Travis). Diff can be found [here](https://www.diffchecker.com/qzgoiqei).

The tool was telling me false again and again, and I was perplexed, and finally, I figured out that it was saying that because it was really NOT sorted.

I will fix those PRs as well.

**Comment by abinashmeher999** [comment]
Cool stuff. Thanks for taking out the time to do it. It would be great with travis :smiley:! I am thinking regexes to check the format of the entry too.

**Comment by icyflame** [comment]
@abinashmeher999 Of course! It will run under the assumption that everything in the README itself is correctly formatted. So, once we can clean everything up, we can set that up as well.

**Comment by abinashmeher999** [comment]
Cool.

**Comment by icyflame** [comment]
@abinashmeher999 Done. One more format problem in the README. Fixed it. Also, opened #126.

**Comment by abinashmeher999** [comment]
@icyflame [This](https://github.com/AGV-IIT-KGP/git-sandbox/pull/127) came up.

**Comment by abinashmeher999** [comment]
#126 Also incorporates these changes. Merging that would be enough. So I guess this can be closed?

**Comment by icyflame** [comment]
@abinashmeher999 Yes. Closing this in favor of #126.

**Pull request closed without merging**
